#!/usr/bin/python3
vRadio = float(input("Ingrese el radio de la circunferencia: "))
pi= 3.14
Longitud = 2 * pi * vRd
Area = pi * (vRd**2)
print("El total de la longitud de la circunferencia es: ", Longitud)
print("El total del area de la circunferencia es: ", Area)
