#!/usr/bin/python3
vBase = float(input("Ingrese la base del triangulo: "))
vAltura = float(input("Ingrese la altura del triangulo: "))
Area  = 1/2 * (vBase * vAltura)
print ("El total del area del triangulo es: ", Area)
